ALTER TABLE roles
    MODIFY COLUMN name ENUM('ROLE_BUYER', 'ROLE_PROVIDER', 'ROLE_ADMIN') NOT NULL;

INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');
